const BLP_MAGIC_NUMBER = tag4"BLP2"

@enum BLPCompression::UInt8 begin
  BLP_COMPRESSION_BLP = 1
  BLP_COMPRESSION_DXTC = 2
  BLP_COMPRESSION_NONE = 3
end

@enum BLPPixelFormat::UInt8 begin
  BLP_PIXEL_FORMAT_DXT1 = 0
  BLP_PIXEL_FORMAT_DXT3 = 1
  BLP_PIXEL_FORMAT_ARGB8888 = 2
  BLP_PIXEL_FORMAT_ARGB1555 = 3
  BLP_PIXEL_FORMAT_ARGB4444 = 4
  BLP_PIXEL_FORMAT_RGB565 = 5
  BLP_PIXEL_FORMAT_A8 = 6
  BLP_PIXEL_FORMAT_DXT5 = 7
  BLP_PIXEL_FORMAT_UNSPECIFIED = 8
  BLP_PIXEL_FORMAT_ARGB2565 = 9
  BLP_PIXEL_FORMAT_UNKNOWN = 10
  BLP_PIXEL_FORMAT_BC5 = 11 # DXGI_FORMAT_BC5_UNORM
end

struct BLPFile
  image::Matrix{RGBA{N0f8}}
  mipmaps::Vector{Matrix{RGBA{N0f8}}}
end
