@bitmask exported = true MagicSchool::UInt32 begin
  PHYSICAL = 1
  HOLY = 2
  FIRE = 4
  NATURE = 8
  FROST = 16
  SHADOW = 32
  ARCANE = 64
end

const HOLYSTRIKE = PHYSICAL | HOLY
const FLAMESTRIKE = PHYSICAL | FIRE
const HOLYFIRE = HOLY | FIRE
const STORMSTRIKE = PHYSICAL | NATURE
const HOLYSTORM = HOLY | NATURE
const FIRESTORM = FIRE | NATURE
const FROSTSTRIKE = PHYSICAL | FROST
const FROSTFIRE = FIRE | FROST
const FROSTSTORM = NATURE | FROST
const SHADOWSTRIKE = PHYSICAL | SHADOW
const TWILIGHT = HOLY | SHADOW
const SHADOWFLAME = FIRE | SHADOW
const PLAGUE = NATURE | SHADOW
const SHADOWFROST = FROST | SHADOW
const DIVINE = HOLY | ARCANE
const SPELLFIRE = FIRE | ARCANE
const SPELLSTORM = NATURE | ARCANE
const SPELLFROST = FROST | ARCANE
const SPELLSHADOW = SHADOW | ARCANE

const ELEMENTAL = FIRE | NATURE | FROST
const MAGIC = HOLY | FIRE | NATURE | FROST | FIRE | SHADOW | ARCANE
const CHAOS = PHYSICAL | HOLY | FIRE | NATURE | FROST | FIRE | SHADOW | ARCANE

export HOLYSTRIKE, FLAMESTRIKE, HOLYFIRE, STORMSTRIKE, HOLYSTORM, FIRESTORM, FROSTSTRIKE, FROSTFIRE, FROSTSTORM, SHADOWSTRIKE, TWILIGHT, SHADOWFLAME, PLAGUE, SHADOWFROST, DIVINE, SPELLFIRE, SPELLSTORM, SPELLFROST, SPELLSHADOW, ELEMENTAL, MAGIC, CHAOS
